package com.fui.cloud.model;

public class JwtRoleAuthoritiesKey extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_role_authorities.oauth_role_id
     *
     * @mbggenerated
     */
    private Long oauthRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_role_authorities.authorities_id
     *
     * @mbggenerated
     */
    private Long authoritiesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_role_authorities.oauth_role_id
     *
     * @return the value of oauth_role_authorities.oauth_role_id
     *
     * @mbggenerated
     */
    public Long getOauthRoleId() {
        return oauthRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_role_authorities.oauth_role_id
     *
     * @param oauthRoleId the value for oauth_role_authorities.oauth_role_id
     *
     * @mbggenerated
     */
    public void setOauthRoleId(Long oauthRoleId) {
        this.oauthRoleId = oauthRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_role_authorities.authorities_id
     *
     * @return the value of oauth_role_authorities.authorities_id
     *
     * @mbggenerated
     */
    public Long getAuthoritiesId() {
        return authoritiesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_role_authorities.authorities_id
     *
     * @param authoritiesId the value for oauth_role_authorities.authorities_id
     *
     * @mbggenerated
     */
    public void setAuthoritiesId(Long authoritiesId) {
        this.authoritiesId = authoritiesId;
    }
}